# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 36181ead05bb5f63a48766ba2929a0f7efd0fb494f9c81ca74ef9cde2d7337200aa93d9a976ae9a42cf7e82e4cb612797c0a397337a7d76964dc98aad23a0a78

test:
  secret_key_base: 10bd161f0ab79d52ba39f8e1166f687637a54c8cdab266325aa1b56ee52236e48940e92df4c8ff8782a5cabcece8025f0cf4b946ea8fa3334fd67c842b7ab99c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
